FROM node:16 AS build

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

FROM build AS dev

# Bundle app source

COPY . .

EXPOSE 3000

CMD [ "node" , "server.js" ]